modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "rarecandylib"
version = "${version}"
displayName = "Rare Candy Lib"
authors = "Waterpicker"
description = '''
'''
#logoFile = ""

[[dependencies.rarecandylib]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rarecandylib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.rarecandylib]]
modId = "cobblemon"
mandatory = false
versionRange = "[1.5.2]"
ordering = "NONE"
side = "BOTH"
